name: 'Remind to update the summary'

on:
  schedule:
    - cron: '0 10 * * MON'
    - cron: '0 12 * * TUE'
    - cron: '0 15 * * FRI'
  workflow_dispatch:

env:
  REMINDER_MESSAGE: "@*People-ops* don't forget to update your latest work items in [TeamOS - What Do You Do?](https://github.com/people-os/team-os-wdyd/blob/master/SUMMARY.md). The summary will be published on Monday, 15 minutes before the company all hands call."
  ZULIP_STREAM: 'aspect/people-ops'
  ZULIP_TOPIC: 'TeamOS - WDYD?'

jobs:
  publish:
    name: 'Send the reminder'
    runs-on: ubuntu-latest
    steps:
      - name: 'Send the message to Zulip'
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ vars.ZULIP_BOT_EMAIL }}
          organization-url: 'https://balena.zulipchat.com'
          to: ${{ env.ZULIP_STREAM }}
          type: 'stream'
          topic: ${{ env.ZULIP_TOPIC }}
          content: ${{ env.REMINDER_MESSAGE }}
