name: 'Remind to update the summary'

on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch:

env:
  REMINDER_STREAM: 'loop/team-os'
  REMINDER_TOPIC: 'TeamOS - WDYD?'
  REMINDER_MESSAGE: 'TODO'

jobs:
  publish:
    name: 'Send the reminder'
    runs-on: ubuntu-latest
    steps:
      - name: 'Send the message to Zulip'
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ vars.ZULIP_BOT_EMAIL }}
          organization-url: 'https://balena.zulipchat.com'
          to: ${{ env.REMINDER_STREAM }}
          type: 'stream'
          topic: ${{ env.REMINDER_TOPIC }}
          content: ${{ env.REMINDER_MESSAGE }}
