name: 'Remind to update the summary'

on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch:

env:
  REMINDER_MESSAGE: 'Just do it!'
  ZULIP_STREAM: '_hack-fridays'
  ZULIP_TOPIC: 'Team-OS What Do You Do? (Hack Friday)'

jobs:
  publish:
    name: 'Send the reminder'
    runs-on: ubuntu-latest
    steps:
      - name: 'Send the message to Zulip'
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ vars.ZULIP_BOT_EMAIL }}
          organization-url: 'https://balena.zulipchat.com'
          to: ${{ env.ZULIP_STREAM }}
          type: 'stream'
          topic: ${{ env.ZULIP_TOPIC }}
          content: ${{ env.REMINDER_MESSAGE }}
